### ISSUE TITLE
Add product with an product addon programatically

### ISSUE THREAD

**Issue by johncarter-** [nextime/woocommerce-better-product-addons#1]
Hi

First, thanks for putting this up, this is a great plugin and your modifications have made it nearly perfect for my use.

I have one question, how would I go about using this plugin to add a product to cart programtically? Is it even possible? I know that Woocommerce has the ability to add products like so:

`public function add_to_cart( $product_id, $quantity, $variation_id = '', $variation = '', $cart_item_data = array() ) {`

How would the product add ons be parsed in this function?

**Comment by nextime** [comment]
Hi John, 
i really never tried to do that, but it's something i will need to do soon, so, i assume i have to test your use..

**Comment by valix85** [comment]
i need some help, i try to catch a product from my cart, i remove it for add it with some addons, a new product is inside a cart with addons array but in cart page i see only my variable product without any addons... i can to do for add many addons in my item cart?

**Comment by valix85** [comment]
My trick for only custom field is:
 in class-product-addon-cart.php at the start paste it:

//valerio i23
if ( isset($_GET['add-to-cart']) and is_numeric($_GET['add-to-cart'])){
$_POST = $_GET;
}
//fine valerio i23

and next do an ajax call in GET with all parameters addon- example:

http://www.example.local/cart/?add-to-cart=8&variation_id=83&attribute_pa_posizione=forno-a-destra&attribute_pa_colore-top=top-109&attribute_pa_colore-ante=anta-01&attribute_pa_maniglia=maniglia-1&addon-8-misura-elemento-a-cm=90&addon-8-misura-elemento-b-cm=45

**Comment by nextime** [comment]
Make sense, can you send a pull request with your changes ( ajax part included )?

**Comment by nextime** [comment]
Moved to https://git.nexlab.net/nextime/woocommerce_bpd/issues
