### ISSUE TITLE
Replace chosen with select2

### ISSUE THREAD

**Issue by TheJotob** [nextime/woocommerce-better-product-addons#11]
Hi,
since WooCommerce switched from the jQuery Plugin chosen to select2 there are some issues regarding this plugin, because it is still using chosen.
Resulting in me not beeing able to switch between visual and text view in the product editing view.
I tried to fix this issue but couldn't find the javascript code to change. Could you help me?
Thanks
Joachim

**Comment by ElyFornoville** [comment]
I have the same problem. Is it possible to have an update fast as we have issues editing our products.

Console error:
Uncaught TypeError: jQuery(...).chosen is not a function
post.php?post=6105&action=edit:1078

**Comment by nextime** [comment]
Please not that i'm not the original author of this plugin, i just shared it as it's under GPL and i think that it's fair to share it, but i'm not actively maintaining it, if anyone will send a patch/poll request i will be appy to apply it, but i will work on it only to fit my own needs and/or on easy to reproduce bugs.

If anyway anyone will point me in how to reproduce the issue, maybe i can give it a look

**Comment by ElyFornoville** [comment]
Who is the official author of this plugin?

Here is how to reproduce it:
1. Install Wordpress latest version
2. Install WooCommerce latest version
3. Install WooCommerce Better Product Addons latest version
4. Add or edit a product
5. Click on antything that requires javascript > Like the publish button or the little arrows to top collapse the tabs or change your editor from text to code. It does not work.
6. In your console you should see the error I posted above.

Thank you for looking at it.

**Comment by nextime** [comment]
I'm using the latest version of wordpress woocommerce and this plugin as it is here, but i can reproduce the issue, this is why i was asking.

This plugin is simply a patched ( a little patch i've done for myself ages ago ) of the "woocommerce product addons" you can find on woothemes

**Comment by TheJotob** [comment]
#12 should fix the problem

**Comment by nextime** [comment]
easy as that? ok then, thanks

**Comment by ElyFornoville** [comment]
Thanks. It fixed the problem.
