### ISSUE TITLE
Maximum number of options

### ISSUE THREAD

**Issue by ruudbwai** [nextime/woocommerce-better-product-addons#2]
There seems to be an upper limit of number of options that can be added...how do I check and increase this? After X amount of options, any new options / add on groups are not added. How do I increase this?

**Comment by ruudbwai** [comment]
scratch that! found this in docs- 

http://docs.woothemes.com/document/problems-with-large-amounts-of-data-not-saving-variations-rates-etc/

changing my php 5.4 max input var to 2000 sorted it.

**Comment by nextime** [comment]
Moved to https://git.nexlab.net/nextime/woocommerce_bpd/issues
