### ISSUE TITLE
checkbox option image field

### ISSUE THREAD

**Issue by andreistefan112** [nextime/woocommerce-better-product-addons#3]
Great work on this plugin. it is really helpful.

I got a question tough and really dont know where to start from.
Is it possible to add a custom image field to checkbox options? For example if customer buys a coffee,, he can always check for one or more options such as eg. sugar, milk, chocolate.cocoa...etc (something like toppings on a pizza) by clicking the images of the options.

I would appreciate any idea on this. Thank in advance!

**Comment by nextime** [comment]
of course it's possible to do that, but it's not a feature i'm not the original author, i will probably not add this feature.

Of course patches are welcome, if anyone will develop the needed code, i will be happy to accept it

**Comment by nextime** [comment]
Moved to https://git.nexlab.net/nextime/woocommerce_bpd/issues
