### ISSUE TITLE
woocommerce_admin_css deprecated

### ISSUE THREAD

**Issue by andsat** [nextime/woocommerce-better-product-addons#9]
receiving this error after activating the plugin:

Notice: The woocommerce_admin_css action is deprecated since version 2.3! Use admin_enqueue_scripts instead. in /var/www/html/dreambed/wp-includes/functions.php on line 3406

the code is actually line 15 in class-product-addon-admin.php

**Comment by nextime** [comment]
Well, it's a notice, not an error, anyway, yes, it needs a refresh
